# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VviRxSDqqU1vhuKnHWyRLQe8wUCYRcS0
"""

from sklearn.feature_extraction.text import CountVectorizer
 

document = ["One Cent, Two Cents, Old Cent, New Cent: All About Money"]
 
# Create a Vectorizer Object

vectorizer = CountVectorizer()
 
vectorizer.fit(document)
 
# Printing the identified Unique words along with their indices

print("Vocabulary: ", vectorizer.vocabulary_)
 
# Encode the Document

vector = vectorizer.transform(document)
 
# Summarizing the Encoded Texts

print("Encoded Document is:")

print(vector.toarray())

